"""empty message

Revision ID: 312d931995cb
Revises: 
Create Date: 2024-11-19 05:39:48.326298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312d931995cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptions', sa.String(), nullable=False))
        batch_op.drop_constraint('assignments_subject_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['subject_id'])
        batch_op.drop_column('description')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('uc_attendance', type_='unique')
        batch_op.drop_constraint('attendance_subject_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('attendance_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['subject_id'])
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('us_grades', type_='unique')
        batch_op.drop_constraint('grades_student_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('grades_subject_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['subject_id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('students_group_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['group_id'])

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint('subjects_teacher_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['teacher_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('subjects_teacher_id_fkey', 'teachers', ['teacher_id'], ['teacher_id'], ondelete='SET NULL')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('students_group_id_fkey', 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grades_subject_id_fkey', 'subjects', ['subject_id'], ['subject_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('grades_student_id_fkey', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('us_grades', ['student_id', 'subject_id', 'date_grade'])

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('attendance_student_id_fkey', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('attendance_subject_id_fkey', 'subjects', ['subject_id'], ['subject_id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('uc_attendance', ['student_id', 'subject_id', 'date_presence'])

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('assignments_subject_id_fkey', 'subjects', ['subject_id'], ['subject_id'], ondelete='CASCADE')
        batch_op.drop_column('descriptions')

    # ### end Alembic commands ###
